/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_marswin89_marsdaemon_nativ_NativeDaemonAPI20 */

#ifndef _Included_com_marswin89_marsdaemon_nativ_NativeDaemonAPI20
#define _Included_com_marswin89_marsdaemon_nativ_NativeDaemonAPI20
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_marswin89_marsdaemon_nativ_NativeDaemonAPI20
 * Method:    doDaemon
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_marswin89_marsdaemon_nativ_NativeDaemonAPI20_doDaemon
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
